//! Waste-domain types, re-exported from `crate::types` for a focused,
//! reviewable surface without changing the original type paths.

pub use crate::types::{
    BatchStatus,
    CompositionEntry,
    ContaminationReport,
    GradeRecord,
    ImpactHistoryEntry,
    ImpactScore,
    Material,
    MaterialComposition,
    OptionalWasteType,
    PendingTransfer,
    PendingTransferStatus,
    ProcessingRecord,
    ProcessingStatus,
    RecyclingGoal,
    SubstitutionRecord,
    TransferApproval,
    TransferApprovalStatus,
    TransferItemType,
    TransferRecord,
    TransferStatus,
    TransferValidationRecord,
    Waste,
    WasteBatch,
    WasteBuilder,
    WasteCertification,
    WasteGrade,
    WasteTransfer,
    WasteType,
};
